import { docs } from "@/.source/server"

export interface Project {
  name: string
  description: string
  cohort: string
  url: string
  docsUrl?: string
  stars?: number
  category: string
}

// Ładowanie projektów z Fumadocs MDX loader
// Fumadocs przechowuje custom frontmatter properties bezpośrednio na obiekcie page
export const projects: Project[] = docs.map((page: any) => {
  return {
    name: (page.name || page.title) as string,
    description: page.description as string,
    cohort: page.cohort as string,
    url: page.url as string,
    docsUrl: page.docsUrl as string | undefined,
    stars: page.stars as number | undefined,
    category: page.category as string,
  }
})

// Stara tablica projektów - zachowana jako backup
export const legacyProjects: Project[] = [
  // Spring 2025 Cohort
  {
    name: "Vecto3d",
    description: "Converts your SVGs into 3D models. Unlike other converters, Vecto3d doesn't charge for exporting.",
    cohort: "Spring 2025",
    url: "https://github.com/lakshaybhushan/vecto3d",
    docsUrl: "https://www.vecto3d.xyz/",
    category: "3D Tool",
  },
  {
    name: "Script Kit",
    description: "A desktop app for launching scripts with an SDK to simplify desktop/API actions and custom prompts.",
    cohort: "Spring 2025",
    url: "https://github.com/johnlindquist/kit",
    docsUrl: "https://www.scriptkit.com/",
    category: "Developer Tool",
  },
  {
    name: "Lenis",
    description: "Lightweight, robust, and performant smooth scroll library with 33K weekly npm downloads.",
    cohort: "Spring 2025",
    url: "https://github.com/darkroomengineering/lenis",
    docsUrl: "https://lenis.darkroom.engineering/",
    category: "Animation",
  },
  {
    name: "Fumadocs",
    description:
      "A beautiful documentation framework for Next.js used by Vercel for Flags SDK, Turborepo docs, and more.",
    cohort: "Spring 2025",
    url: "https://github.com/fuma-nama/fumadocs",
    docsUrl: "https://fumadocs.dev/",
    category: "Documentation",
  },
  {
    name: "Shadcn-table",
    description: "Quick setup for shadcn/ui table with server side pagination, sorting, and filtering.",
    cohort: "Spring 2025",
    url: "https://github.com/sadmann7/shadcn-table",
    docsUrl: "https://tablecn.com/",
    category: "UI Component",
  },
  {
    name: "Morphic",
    description: "AI-powered search engine with generative UI. Simple deployment with just two API keys needed.",
    cohort: "Spring 2025",
    url: "https://github.com/miurla/morphic",
    docsUrl: "https://www.morphic.sh/",
    category: "AI",
  },
  {
    name: "Zola",
    description: "Open-source AI chat app. Fast, clean, multi-model, and easy to use for more accessible AI.",
    cohort: "Spring 2025",
    url: "https://github.com/ibelick/zola",
    docsUrl: "https://www.zola.chat/",
    category: "AI",
  },
  {
    name: "Valibot",
    description: "Validate data easily using a schema with 7.5K stars and nearly 1 million weekly npm downloads.",
    cohort: "Spring 2025",
    url: "https://github.com/fabian-hiller/valibot",
    docsUrl: "https://valibot.dev/",
    category: "Validation",
  },
  {
    name: "shadcn-form",
    description: "Build forms faster combining shadcn/ui with react-hook-form and zod. 2.2K GitHub stars.",
    cohort: "Spring 2025",
    url: "https://github.com/hasanharman/form-builder",
    docsUrl: "https://www.shadcn-form.com/",
    category: "UI Component",
  },
  {
    name: "jsPDF",
    description: "First PDF generation library in JS with nearly 2 million weekly npm downloads. Used by NASA.",
    cohort: "Spring 2025",
    url: "https://github.com/parallax/jsPDF",
    docsUrl: "https://www.npmjs.com/package/jspdf",
    category: "PDF",
  },
  {
    name: "LobeChat",
    description:
      "Modern AI chat framework with 60k+ stars supporting multiple AI providers, knowledge management, and multimodal plugins.",
    cohort: "Spring 2025",
    url: "https://github.com/lobehub/lobe-chat",
    docsUrl: "https://lobechat.com",
    category: "AI",
  },
  {
    name: "Milkdown",
    description: "WYSIWYG markdown editor with nearly 10k stars and over 17k weekly npm downloads.",
    cohort: "Spring 2025",
    url: "https://github.com/Milkdown/milkdown",
    docsUrl: "https://milkdown.dev/",
    category: "Editor",
  },
  {
    name: "KokonutUI",
    description: "Collection of components that can be installed with shadcn/ui CLI or opened in v0 for customization.",
    cohort: "Spring 2025",
    url: "https://github.com/kokonut-labs/kokonutui",
    docsUrl: "https://kokonutui.com/",
    category: "UI Library",
  },
  {
    name: "nuqs",
    description: "Type-safe search params state manager for React frameworks with over 300K weekly npm downloads.",
    cohort: "Spring 2025",
    url: "https://github.com/47ng/nuqs",
    docsUrl: "https://nuqs.47ng.com/",
    category: "State Management",
  },
  {
    name: "Nemo",
    description: "Helps Next.js developers understand middleware composition with almost 5K weekly npm downloads.",
    cohort: "Spring 2025",
    url: "https://github.com/z4nr34l/nemo",
    docsUrl: "https://nemo.zanreal.com/",
    category: "Middleware",
  },
  {
    name: "RetroUI",
    description: "Open source UI library based on React, Next.js, and shadcn/ui with retro aesthetic.",
    cohort: "Spring 2025",
    url: "https://github.com/Logging-Stuff/RetroUI",
    docsUrl: "https://retroui.dev/",
    category: "UI Library",
  },
  {
    name: "Tweakcn",
    description: "Generate and customize shadcn/ui themes using AI with 2.5K+ stars.",
    cohort: "Spring 2025",
    url: "https://github.com/jnsahaj/tweakcn",
    docsUrl: "https://tweakcn.com/",
    category: "Design Tool",
  },
  {
    name: "CourseLit",
    description:
      "Platform for building and selling digital products on your website with all infrastructure open source.",
    cohort: "Spring 2025",
    url: "https://github.com/codelitdev/courselit",
    docsUrl: "https://courselit.app/",
    category: "E-commerce",
  },
  {
    name: "Comp AI",
    description:
      "Open source compliance automation platform as an alternative to Vanta & Drata with 1000+ commits in 90 days.",
    cohort: "Spring 2025",
    url: "https://github.com/trycompai/comp",
    docsUrl: "https://trycomp.ai/",
    category: "Compliance",
  },
  {
    name: "EsJS",
    description:
      "Programming language with Spanish syntax that compiles to JS for Spanish-speakers learning programming.",
    cohort: "Spring 2025",
    url: "https://github.com/es-js/esjs",
    docsUrl: "https://editor.esjs.dev/",
    category: "Programming Language",
  },
  {
    name: "Gridiron Survivor",
    description: "Community of open source builders creating projects to help build resumes and land jobs.",
    cohort: "Spring 2025",
    url: "https://github.com/LetsGetTechnical/elecretanta",
    docsUrl: "https://elfgorithm.vercel.app/",
    category: "Community",
  },
  {
    name: "Frontpage",
    description: "Federated link aggregator serving as the defacto link-aggregation website for the Bluesky community.",
    cohort: "Spring 2025",
    url: "https://github.com/likeandscribe/frontpage",
    docsUrl: "https://frontpage.fyi/",
    category: "Social",
  },

  // Summer 2025 Cohort
  {
    name: "OpenCut",
    description: "Browser-based video editor that feels like CapCut, but open source with over 27k GitHub stars.",
    cohort: "Summer 2025",
    url: "https://github.com/OpenCut-app/OpenCut",
    docsUrl: "https://opencut.app",
    category: "Video Editor",
  },
  {
    name: "Inbox Zero",
    description: "Open-source AI assistant that helps clean up your inbox and stay on top of tasks.",
    cohort: "Summer 2025",
    url: "https://github.com/elie222/inbox-zero",
    docsUrl: "https://www.getinboxzero.com/",
    category: "Productivity",
  },
  {
    name: "8bitcn/ui",
    description: "Retro-themed component library with 8-bit game vibes and pixel-perfect design.",
    cohort: "Summer 2025",
    url: "https://github.com/TheOrcDev/8bitcn-ui",
    docsUrl: "https://www.8bitcn.com/",
    category: "UI Library",
  },
  {
    name: "React Wheel Picker",
    description: "Clean, mobile-style picker for React apps. Lightweight, smooth, and ready to drop into any form.",
    cohort: "Summer 2025",
    url: "https://github.com/ncdai/react-wheel-picker",
    docsUrl: "https://react-wheel-picker.chanhdai.com/",
    category: "UI Component",
  },
  {
    name: "Mobx",
    description: "Battle-tested state manager in JavaScript with 28k+ stars and nearly 2M weekly NPM downloads.",
    cohort: "Summer 2025",
    url: "https://github.com/mobxjs/mobx",
    docsUrl: "https://mobx.js.org/",
    category: "State Management",
  },
  {
    name: "Workout Cool",
    description: "Plan and build workouts with a slick UI and smart recommendations. 5.2k GitHub stars.",
    cohort: "Summer 2025",
    url: "https://github.com/Snouzy/workout-cool",
    docsUrl: "https://workout.cool/en",
    category: "Fitness",
  },
  {
    name: "OSS.Now",
    description: "Platform to showcase and grow open source projects. Discover what's trending or share your own.",
    cohort: "Summer 2025",
    url: "https://github.com/ossdotnow/ossdotnow",
    docsUrl: "https://oss.now/",
    category: "Discovery",
  },
  {
    name: "Invoicely",
    description: "Easy way to create beautiful invoices fast. Fully open source and built for freelancers.",
    cohort: "Summer 2025",
    url: "https://github.com/legions-developer/invoicely",
    docsUrl: "https://invoicely.gg/",
    category: "Finance",
  },
  {
    name: "Fancy Components",
    description: "Polished UI components with extra flair with 2.1k GitHub stars.",
    cohort: "Summer 2025",
    url: "https://github.com/danielpetho/fancy",
    docsUrl: "https://fancycomponents.dev/",
    category: "UI Library",
  },
  {
    name: "Inbound",
    description:
      "Simple and powerful email for developers. Hook into messages with webhooks and treat emails like code.",
    cohort: "Summer 2025",
    url: "https://github.com/R44VC0RP/inbound",
    docsUrl: "https://inbound.new/",
    category: "Email",
  },
  {
    name: "Resume Matcher",
    description: "Tailors your job search to fit your skillset with over 20k GitHub stars.",
    cohort: "Summer 2025",
    url: "https://github.com/srbhr/Resume-Matcher",
    docsUrl: "https://resumematcher.fyi/",
    category: "Career",
  },
  {
    name: "Pigsty",
    description:
      "Open source, local-first PostgreSQL distribution and alternative to managed databases with 4k+ stars.",
    cohort: "Summer 2025",
    url: "https://github.com/pgsty/pigsty",
    docsUrl: "https://pgsty.com/",
    category: "Database",
  },
  {
    name: "Analog",
    description: "AI-first calendar that learns how you schedule, not just what you schedule.",
    cohort: "Summer 2025",
    url: "https://github.com/analogdotnow/Analog",
    docsUrl: "https://analog.now/",
    category: "Productivity",
  },
  {
    name: "Kanba",
    description: "Clean, self-hostable task manager that's easy to use with strong community support.",
    cohort: "Summer 2025",
    url: "https://github.com/Uaghazade1/kanba",
    docsUrl: "https://kanba.co/",
    category: "Productivity",
  },
  {
    name: "Nativewind",
    description: "Brings Tailwind CSS design to React Native. 6k+ stars and makes styling fast and enjoyable.",
    cohort: "Summer 2025",
    url: "https://github.com/nativewind/website",
    docsUrl: "https://www.nativewind.dev/",
    category: "React Native",
  },
  {
    name: "Dysperse",
    description: "Next-generation productivity app with AI-powered labeling and task creation.",
    cohort: "Summer 2025",
    url: "https://github.com/dysperse/dysperse",
    docsUrl: "https://dysperse.com/",
    category: "Productivity",
  },
  {
    name: "React Native Reusables",
    description: "UI components built with Nativewind and shadcn/ui, optimized for accessibility and ease.",
    cohort: "Summer 2025",
    url: "https://github.com/mrzachnugent/react-native-reusables",
    docsUrl: "https://www.reactnativereusables.com/",
    category: "React Native",
  },
  {
    name: "Toolwind",
    description: "Go-to registry for Tailwind CSS plugins trusted across projects and communities.",
    cohort: "Summer 2025",
    url: "https://github.com/toolwind",
    docsUrl: "https://toolwind.com/",
    category: "Tailwind",
  },
  {
    name: "Ikiform",
    description: "Open source alternative to Google Forms with modern UX, flexible, and easy to host.",
    cohort: "Summer 2025",
    url: "https://github.com/preetsuthar17/Ikiform",
    docsUrl: "https://www.ikiform.com/",
    category: "Forms",
  },
  {
    name: "Motia",
    description: "Backend framework for building APIs, events, and agents, built for speed.",
    cohort: "Summer 2025",
    url: "https://github.com/motiadev/motia",
    docsUrl: "https://motia.dev/",
    category: "Backend",
  },
  {
    name: "Circle",
    description: "Clean, self-hostable project and issue tracker. Perfect for solo developers or small teams.",
    cohort: "Summer 2025",
    url: "https://github.com/ln-dev7/circle",
    docsUrl: "https://circle.lndev.me/",
    category: "Project Management",
  },
  {
    name: "Electerm",
    description: "Cross-platform terminal for SSH, SFTP, and serial with 12k+ stars.",
    cohort: "Summer 2025",
    url: "https://github.com/electerm/electerm",
    docsUrl: "https://electerm.html5beta.com/",
    category: "Terminal",
  },
  {
    name: "Tutor GPT",
    description: "AI tutor that adapts to the student for personalized learning.",
    cohort: "Summer 2025",
    url: "https://github.com/plastic-labs/tutor-gpt",
    docsUrl: "https://chat.bloombot.ai/auth",
    category: "Education",
  },
  {
    name: "Alinea",
    description: "Git-based CMS built for Next.js. Clean, modern, and great for developers.",
    cohort: "Summer 2025",
    url: "https://github.com/alineacms/alinea",
    docsUrl: "https://alineacms.com/",
    category: "CMS",
  },
  {
    name: "Spectrum UI",
    description: "Instantly copy-pasteable UI components for your projects with nearly 1k stars.",
    cohort: "Summer 2025",
    url: "https://github.com/arihantcodes/spectrum-ui",
    docsUrl: "http://ui.spectrumhq.in/",
    category: "UI Library",
  },
  {
    name: "Taskmaster",
    description: "AI-powered task management system with nearly 20k+ GitHub stars.",
    cohort: "Summer 2025",
    url: "https://github.com/eyaltoledano/claude-task-master",
    docsUrl: "https://www.task-master.dev/",
    category: "Productivity",
  },
  {
    name: "Bounty",
    description:
      "Platform to help developers find jobs and companies find talent. Simple, fast, and designed for builders.",
    cohort: "Summer 2025",
    url: "https://github.com/ripgrim/bounty.new",
    docsUrl: "https://bounty.new/",
    category: "Career",
  },
  {
    name: "SimpMusic",
    description: "Open source, minimalist music player.",
    cohort: "Summer 2025",
    url: "https://github.com/maxrave-dev/SimpMusic",
    docsUrl: "https://simpmusic.org/",
    category: "Music",
  },

  // Fall 2025 Cohort
  {
    name: "Claude Code Templates",
    description:
      "First dedicated library of production-ready Claude Code components with 7,000+ stars and 100,000+ downloads.",
    cohort: "Fall 2025",
    url: "https://github.com/davila7/claude-code-templates",
    docsUrl: "https://www.aitmpl.com/agents",
    category: "AI",
  },
  {
    name: "Ora Browser",
    description:
      "Open-source Swift-built macOS browser delivering Arc-style experience with native speed and 960 GitHub stars.",
    cohort: "Fall 2025",
    url: "https://github.com/the-ora/browser",
    docsUrl: "https://orabrowser.com",
    category: "Browser",
  },
  {
    name: "Databuddy",
    description: "Open-source analytics tool offering a simpler alternative to PostHog with nearly 2,000 commits.",
    cohort: "Fall 2025",
    url: "https://github.com/databuddy-analytics/Databuddy",
    docsUrl: "https://www.databuddy.cc",
    category: "Analytics",
  },
  {
    name: "OSSTag",
    description: "Open-source TypeScript and Bun-powered alternative to Google Tag Manager focusing on performance.",
    cohort: "Fall 2025",
    url: "https://github.com/opentagmanager/osstag",
    docsUrl: "https://www.osstag.com/",
    category: "Analytics",
  },
  {
    name: "WAV0",
    description: "First open-source, AI-native music studio for the web with full DAW-level editing.",
    cohort: "Fall 2025",
    url: "https://github.com/fluid-tools/wav0",
    docsUrl: "https://wav0.app",
    category: "Music",
  },
  {
    name: "Sparka",
    description: "Production-ready AI chat template with 700+ stars helping teams build AI apps 10x faster.",
    cohort: "Fall 2025",
    url: "https://github.com/FranciscoMoretti/sparka",
    docsUrl: "https://www.sparka.ai/",
    category: "AI",
  },
  {
    name: "Memos",
    description: "Open-source, self-hosted note-taking platform with 44K+ stars and 400+ contributors.",
    cohort: "Fall 2025",
    url: "https://github.com/usememos/memos",
    docsUrl: "https://www.usememos.com/",
    category: "Notes",
  },
  {
    name: "Wora",
    description: "Design-centric, cross-platform lossless audio player built with Next.js and Electron.",
    cohort: "Fall 2025",
    url: "https://github.com/playwora/wora",
    docsUrl: "https://wora.app/",
    category: "Music",
  },
  {
    name: "Tinte",
    description:
      "Open-source theme generator with 2,000 active users and 468 GitHub stars for VS Code, Shadcn/UI, and more.",
    cohort: "Fall 2025",
    url: "https://github.com/Railly/tinte",
    docsUrl: "https://www.tinte.dev",
    category: "Design Tool",
  },
  {
    name: "Animate UI",
    description: "Open-source animated React components with TailwindCSS and Motion. 2,600+ stars.",
    cohort: "Fall 2025",
    url: "https://github.com/imskyleen/animate-ui",
    docsUrl: "https://animate-ui.com",
    category: "UI Library",
  },
  {
    name: "Element Plus",
    description: "Well-designed Vue component library with strong community support and frequent updates.",
    cohort: "Fall 2025",
    url: "https://github.com/element-plus/element-plus",
    docsUrl: "https://element-plus.org/",
    category: "UI Library",
  },
  {
    name: "Scira AI",
    description: "Open-source AI search engine with 60K+ monthly users, 1M+ searches, and 10.7K GitHub stars.",
    cohort: "Fall 2025",
    url: "https://github.com/zaidmukaddam/scira",
    docsUrl: "https://scira.ai",
    category: "AI",
  },
  {
    name: "Lucide Animated",
    description: "Open-source collection of smooth animated icons with 5,000+ GitHub stars.",
    cohort: "Fall 2025",
    url: "https://github.com/pqoqubbw/icons",
    docsUrl: "https://lucide-animated.com",
    category: "Icons",
  },
  {
    name: "Intent UI",
    description: "Accessible React components built on React Aria with TailwindCSS for clean, customizable styling.",
    cohort: "Fall 2025",
    url: "https://github.com/irsyadadl/intentui",
    docsUrl: "https://intentui.com",
    category: "UI Library",
  },
  {
    name: "Gitvizz",
    description: "Transforms any GitHub repository into an interactive visual graph with 100+ stars.",
    cohort: "Fall 2025",
    url: "https://github.com/adithya-s-k/GitVizz",
    docsUrl: "https://www.gitvizz.com/",
    category: "Developer Tool",
  },
  {
    name: "Triplex",
    description: "Framework that lets developers visually explore and edit React components, bridging 2D and 3D.",
    cohort: "Fall 2025",
    url: "https://github.com/pmndrs/triplex/",
    docsUrl: "https://triplex.dev/",
    category: "Developer Tool",
  },
  {
    name: "Better T Stack",
    description: "Modern CLI for scaffolding type-safe TypeScript projects with 3.8K stars and 60K+ npm downloads.",
    cohort: "Fall 2025",
    url: "https://github.com/AmanVarshney01/create-better-t-stack",
    docsUrl: "https://www.better-t-stack.dev/",
    category: "CLI Tool",
  },
  {
    name: "Billing SDK",
    description: "Open-source toolkit for subscriptions and billing with 200+ stars and thousands of users.",
    cohort: "Fall 2025",
    url: "https://github.com/dodopayments/billingsdk",
    docsUrl: "https://billingsdk.com/",
    category: "Payments",
  },
  {
    name: "Publicat",
    description:
      "Plug-and-play tool that turns CSV bibliographies into interactive journal explorers for humanities researchers.",
    cohort: "Fall 2025",
    url: "https://github.com/KGeorgii/Publicat",
    docsUrl: "https://publicat.vercel.app/",
    category: "Research",
  },
  {
    name: "HelixDB",
    description: "Rust-built graph-vector database with 1,900+ commits and 300+ member community.",
    cohort: "Fall 2025",
    url: "https://github.com/HelixDB/helix-db",
    docsUrl: "https://www.helix-db.com",
    category: "Database",
  },
  {
    name: "Yamada UI",
    description:
      "UI library with locally downloadable components and W3C-compliant accessibility supporting 30+ languages.",
    cohort: "Fall 2025",
    url: "https://github.com/yamada-ui/yamada-ui",
    docsUrl: "https://yamada-ui.com",
    category: "UI Library",
  },
  {
    name: "Tailark",
    description: "Collection of 300+ modern marketing block kits with 1.8K+ stars and 65,000+ users.",
    cohort: "Fall 2025",
    url: "https://github.com/tailark/blocks",
    docsUrl: "https://tailark.com",
    category: "UI Library",
  },
  {
    name: "OmniLens",
    description: "Self-hosted monitoring dashboard for GitHub Actions workflows with validated CI metrics.",
    cohort: "Fall 2025",
    url: "https://github.com/OmniLens/OmniLens",
    docsUrl: "https://www.omnilens.xyz",
    category: "DevOps",
  },
  {
    name: "Conduit",
    description: "Open-source AI chat app for iOS and Android built on top of OpenWebUI.",
    cohort: "Fall 2025",
    url: "https://github.com/cogwheel0/conduit",
    docsUrl: "https://cogwheel.app/",
    category: "AI",
  },
  {
    name: "Helixque",
    description: "Open-source real-time video chat platform for professional matching built with Next.js and WebRTC.",
    cohort: "Fall 2025",
    url: "https://github.com/HXQLabs/Helixque",
    docsUrl: "https://helixque-live.vercel.app/",
    category: "Communication",
  },
  {
    name: "Marble",
    description: "Simple, flexible headless CMS with 480+ signups and 20 contributors.",
    cohort: "Fall 2025",
    url: "https://github.com/usemarble/marble",
    docsUrl: "https://marblecms.com",
    category: "CMS",
  },
  {
    name: "0 Finance",
    description: "First fully open source, forkable business savings account with on-chain yield.",
    cohort: "Fall 2025",
    url: "https://github.com/different-ai/zero-finance",
    docsUrl: "https://0.finance",
    category: "Finance",
  },
  {
    name: "Pattern Craft",
    description: "Open-source library of pure-CSS and Tailwind background patterns with 2.4K+ stars.",
    cohort: "Fall 2025",
    url: "https://github.com/megh-bari/pattern-craft",
    docsUrl: "https://patterncraft.fun/",
    category: "Design Tool",
  },
  {
    name: "Teak",
    description: "Open, privacy-friendly tool for designers to capture and preserve visual inspiration.",
    cohort: "Fall 2025",
    url: "https://github.com/praveenjuge/teak",
    docsUrl: "https://teakvault.com",
    category: "Design Tool",
  },
]

export function formatStars(stars: number | undefined): string {
  if (stars === undefined) {
    return "—"
  }
  if (stars >= 1000) {
    return `${(stars / 1000).toFixed(0)}k`
  }
  return stars.toString()
}
